apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer-service
  namespace: kafka
spec:
  ports:
    - port: 8080
  selector:
    app: kafka-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
          image: z0rg3d/kafka-consumer:latest
          name: kafka-consumer
          ports:
            - containerPort: 8080
