apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer-service
  namespace: kafka
spec:
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: kafka-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: consumer
          image: z0rg3d/kafka-consumer:latest
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
          ports:
            - containerPort: 8090
          resources:
            requests:
              cpu: 100m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-consumer-autoscaler
  namespace: kafka
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-consumer
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
