apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka
spec:
  serviceName: kafka-service
  replicas: 3
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      terminationGracePeriodSeconds: 60
      hostname: kafka-broker
      containers:
        - env:
          - name: BROKER_ID_COMMAND
            value: "[[ `hostname` =~ -([0-9]+) ]] && echo ${BASH_REMATCH[1]}"
          - name: HOSTNAME_COMMAND
            value: hostname
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service:2181
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094"
          - name: KAFKA_LISTENERS
            value: INSIDE://:9092,OUTSIDE://:9094
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: INSIDE
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "false"
          - name: KAFKA_CREATE_TOPICS
            value: "email:5:2,message:5:2,push:5:2,socialmedia:5:2,calendar:5:2,app:5:2,news:5:2"
          - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
            value: "false"
          - name: KAFKA_CONTROLLER_SOCKET_TIMEOUT_MS
            value: "30000"
          image: wurstmeister/kafka:latest
          name: kafka-broker
          ports:
            - containerPort: 9092
          resources:
            requests:
              cpu: 250m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-autoscaler
  namespace: kafka
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: kafka-broker
  minReplicas: 3
  maxReplicas: 9
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
