apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
        - env:
          - name: KAFKA_BROKER _ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service:2181
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://:9092
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka-broker:9092
          - name: KAFKA_CREATE_TOPICS
            value: "email:3:1,sms:3:1,push:3:1,action:3:1,system:3:1"
          image: wurstmeister/kafka:latest
          name: kafka-broker
          ports:
            - containerPort: 9092