apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka
spec:
  serviceName: kafka-service
  replicas: 3
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
        - env:
          - name: BROKER_ID_COMMAND
            value: "[[ `hostname` =~ -([0-9]+) ]] && echo ${BASH_REMATCH[1]}"
          - name: HOSTNAME_COMMAND
            value: hostname
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service:2181
          # - name: KAFKA_LISTENERS
          #   value: PLAINTEXT://:9092
          - name: KAFKA_ADVERTISED_LISTENERS
            # value: "PLAINTEXT://kafka-broker-_{BROKER_ID_COMMAND}.kafka.pod.cluster.local:9092"
            value: "INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094"
          - name: KAFKA_LISTENERS
            value: INSIDE://:9092,OUTSIDE://:9094
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: INSIDE
          - name: KAFKA_CREATE_TOPICS
            value: "email:5:2,sms:5:2,push:5:2,action:5:2,system:5:2"
          image: wurstmeister/kafka:latest
          name: kafka-broker
          ports:
            - containerPort: 9092
          resources:
            requests:
              cpu: 1000m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-autoscaler
  namespace: kafka
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: kafka-broker
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
