apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer-service
  namespace: kafka
spec:
 
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: kafka-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: producer
          image: z0rg3d/kafka-producer:latest
          ports:
            - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-producer-ingress
  labels:
    name: kafka-producer-ingress
  namespace: kafka
spec:
  rules:
  - host: localhost
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kafka-producer-service
              port: 
                number: 80

