apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer-service
  namespace: kafka
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: kafka-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: producer
          image: z0rg3d/kafka-producer:latest
          ports:
            - containerPort: 5000
