apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer-service
  namespace: kafka
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kafka-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: producer
          image: z0rg3d/kafka-producer:latest
          ports:
            - containerPort: 8080
